# Configure a default setup of Home Assistant (frontend, api, etc)

homeassistant:
  name: Home
  latitude: !secret zone_davecave_lat
  longitude: !secret zone_davecave_long
  time_zone: "America/Los_Angeles"
  temperature_unit: C
  unit_system: metric
  currency: USD
  packages: !include_dir_named include
  allowlist_external_dirs:
    - /config

default_config:

# group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
# scene: !include scenes.yaml
# camera: !include cameras.yaml
# zone: !include zones.yaml

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include themes.yaml

logger:
  default: warning
  logs:
    homeassistant.components.websocket_api: fatal
    homeassistant.components.camera: fatal
    # amcrest: debug
    # homeassistant.components.amcrest: debug

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

updater:

downloader:
  download_dir: downloads

#   media_dirs:
# media: /config/media

# Activiate the configuration editor
config:

system_health:

media_source:

stream:

ffmpeg:

browser_mod:
  prefix: "browser_"
  devices:
    ac39bba2-5650e008:
      name: "browser_davebook_pro"
    0d518399-1bf39487:
      name: "browser_davecom"

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret ha_base_url
    service_name: google_translate_say

lovelace:
  mode: yaml
  # resources: !include lovelace/resources.yaml
  dashboards:
    lovelace-davecave:
      title: "DaveCave"
      icon: "mdi:account-group"
      filename: ui-lovelace-davecave.yaml
      show_in_sidebar: true
      require_admin: false
      mode: yaml
    lovelace-mobile:
      title: "DaveCave Mobile"
      icon: mdi:cellphone
      filename: ui-lovelace-mobile.yaml
      show_in_sidebar: true
      require_admin: false
      mode: yaml
    # lovelace-guest:
    #   title: "Guest"
    #   icon: "mdi:account-group-outline"
    #   filename: ui-lovelace-guest.yaml
    #   show_in_sidebar: false
    #   require_admin: false
    #   mode: yaml
    lovelace-main:
      title: "V2"
      icon: mdi:hexagram
      filename: ui-lovelace-main.yaml
      show_in_sidebar: false
      require_admin: true
      mode: yaml
    lovelace-homekit:
      title: "HomeKit"
      icon: mdi:apple-ios
      filename: ui-lovelace-homekit.yaml
      show_in_sidebar: false
      require_admin: true
      mode: yaml
    lovelace-example:
      title: "Example"
      icon: mdi:apple-ios
      filename: ui-lovelace-example.yaml
      show_in_sidebar: false
      require_admin: true
      mode: yaml
  resources: # HACS
    - url: /hacsfiles/rgb-light-card/card.js
      type: module
    - url: /hacsfiles/scheduler-card/scheduler-card.js
      type: module
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/bignumber-card/bignumber-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/spotify-card/spotify-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/stack-in-card/stack-in-card.js
      type: module
    - url: /hacsfiles/decluttering-card/decluttering-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/deep-press/deep-press.js
      type: module
    - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
      type: module
    - url: /hacsfiles/light-entity-card/light-entity-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /browser_mod.js
      type: module
    - url: /hacsfiles/light-popup-card/light-popup-card.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    # lovelace-settings:
    #   title: "Guest"
    #   icon: "mdi:cog"
    #   filename: ui-lovelace-guest.yaml
    #   show_in_sidebar: false
    #   mode: yaml
    # lovelace-test:
    #   title: "Test"
    #   icon: "mdi:cog"
    #   filename: ui-lovelace-test.yaml
    #   show_in_sidebar: true
    #   require_admin: true
    #   mode: yaml
    # lovelace-cast:
    #   title: "Cast"
    #   icon: "mdi:cast"
    #   filename: ui-lovelace-cast.yaml
    #   show_in_sidebar: true
    #   require_admin: true
    #   mode: yaml

person:
  - name: Dave
    id: dave
    device_trackers:
      - device_tracker.davecom

  - name: Ebony
    id: ebony
    device_trackers:
      - device_tracker.ebonycom

lock:
  - platform: template
    name: Door
    value_template: >
      {{ states('binary_sensor.front_door_sensor_status') }}
    lock:
      service: script.turn_on
      entity_id: script.lock_door_if_closed
    unlock:
      service: script.turn_on
      entity_id: script.unlock_the_door

alert:
  front_door:
    name: Front Door is open
    # done_message: Garage is closed
    entity_id: input_boolean.front_door_sensor_status
    state: "on"
    repeat: 5
    # can_acknowledge: true
    skip_first: true
    notifiers:
      - mobile_app_davecom

proximity:
  home:
    # ignored_zones:
    #   - jaz
    #   - deandre
    #   - davecave
    #   - noodle_house
    devices:
      - device_tracker.davecom
      - device_tracker.ebonycom
    unit_of_measurement: mi
    tolerance: 50

media_player:
  - platform: androidtv
    name: Living Room TV
    host: !secret living_room_tv_ip

    # device_class: androidtv
    # host: 192.
    # adbkey: "/config/android/adbkey"
    # exclude_unnamed_apps: true
    # apps:
    # com.amazon.tv.launcher: "Fire TV"
    # some.background.app:  # this will never show up in the sources list
    # another.background.app: ""

# Amcrest
amcrest:
  - host: !secret ip_amcrest_living_room
    name: "Amcrest Living Room"
    username: !secret amcrest_username
    password: !secret amcrest_password
    # port: 80
    # stream_source: rtsp
    # stream_source: mjpeg
    # resolution: low
    binary_sensors:
      # - motion_detected
      - online
      - motion_detected_polled
    sensors:
      - sdcard
      - ptz_preset

  - host: !secret ip_amcrest_driveway
    name: "Amcrest Driveway"
    username: !secret amcrest_username
    password: !secret amcrest_password
    binary_sensors:
      - online
      - motion_detected_polled
    sensors:
      - sdcard

  # - host: !secret ip_amcrest_bedroom
  #   name: "Amcrest Bedroom"
  #   username: !secret amcrest_username
  #   password: !secret amcrest_password
  # stream_source: rtsp, snapshot
  # port: 554, 3777, 80
  # resolution: low, high
  # binary_sensors:
  #   - online
  #   - motion_detected_polled
  # sensors:
  #   - sdcard
  # switches:
  #   - privacy_mode

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

spotcast:
  sp_dc: !secret spotcast_sp_dc
  sp_key: !secret spotcast_sp_key

# Rest Commands
rest_command:
  # Assistant Relay Commands
  assistant_broadcast:
    url: !secret assistant_relay_url
    method: POST
    content_type: "application/json"
    payload: '{"command":"{{ command }}", "user":"Dave Lambe", "broadcast":true}'

  assistant_converse:
    url: !secret assistant_relay_url
    method: POST
    content_type: "application/json"
    payload: '{"command":"{{ command }}", "user":"Dave Lambe", "converse":true}'

  assistant_relay:
    url: !secret assistant_relay_url
    method: POST
    content_type: "application/json"
    payload: '{"command":"{{ command }}", "user":"Dave Lambe"}'

notify:
  - name: dave_lambe_gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email_address_dave
    encryption: starttls
    username: !secret email_address_dave
    password: !secret email_address_pw_dave
    recipient:
      - !secret email_address_dave
    sender_name: "Home Assistant Priority Notifier"
