button_card_templates: !include button_card_templates.yaml

views:
  - type: custom:grid-layout
    path: 0
    layout:
      #default
      grid-gap: var(--custom-layout-card-padding)
      grid-template-columns: repeat(4, 1fr) 0
      grid-template-rows: 0 repeat(2, fit-content(100%))
      grid-template-areas: |
        "sidebar  .           .        .      ."
        "sidebar  livingroom  kitchen  home   ."
        "sidebar  bedroom     other    media  ."
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-gap: calc(var(--custom-layout-card-padding) * 1.7)
          grid-template-columns: 0 repeat(2, 1fr) 0
          grid-template-rows: 0 repeat(4, fit-content(100%)) 0fr
          grid-template-areas: |
            ".  .           .        ."
            ".  sidebar     sidebar  ."
            ".  livingroom  home     ."
            ".  kitchen     other    ."
            ".  bedroom     media    ."
            ".  .           .        ."
        #portrait
        "(max-width: 1200px)":
          grid-gap: var(--custom-layout-card-padding)
          grid-template-columns: repeat(3, 1fr) 0
          grid-template-rows: 0 repeat(3, fit-content(100%)) 0fr
          grid-template-areas: |
            "sidebar  .           .        ."
            "sidebar  livingroom  home     ."
            "sidebar  kitchen     other    ."
            "sidebar  bedroom     media    ."
            "sidebar  .           .        ."
    cards:
      - type: custom:button-card
        styles: #extra_styles fix
          card:
            - display: none

      #################################################
      #                                               #
      #                    SIDEBAR                    #
      #                                               #
      #################################################

      - type: vertical-stack
        view_layout:
          grid-area: sidebar
        cards:
          - type: custom:button-card
            entity: sensor.template_sidebar
            template: sidebar_template

          - type: grid
            cards:
              - type: button
                icon: mdi:cctv
                tap_action: !include popup/sidebar_security.yaml
                hold_action:
                  action: none

              - type: button
                icon: mdi:information-outline
                tap_action: !include popup/sidebar_information.yaml
                hold_action:
                  action: none

              - type: button
                icon: mdi:arrow-up-bold-circle-outline
                tap_action: !include popup/sidebar_update.yaml
                # tap_action:
                #   action: call-service
                #   service: frontend.reload_themes
                
                # hold_action:
                #   action: call-service
                #   service: homeassistant.update_entity
                #   service_data:
                #     entity_id: sensor.hacs

      #################################################
      #                                               #
      #                  Living Room                  #
      #                                               #
      #################################################

      - type: grid
        title: Living Room
        view_layout:
          grid-area: livingroom
        columns: 2
        cards:
          
          - type: custom:button-card
            template:
              - light
              - icon_light_group
            entity: light.living_room_lights #living_room_lights
            name: Lights
            tap_action: !include popup/lights_livingroom.yaml
            hold_action:
              action: toggle
              haptic: medium

          # - type: custom:button-card
          #   entity: climate.thermostat
          #   name: Heating
          #   tap_action: !include popup/sovrum_klimat.yaml
          #   hold_action:
          #     !include popup/sovrum_klimat.yaml
          #   template:
          #     - base
          #     - icon_climate
          #     - climate
          #   variables:
          #     circle_input: >
          #       [[[
          #         if (entity) {
          #           return entity.state == 'heat' ?
          #             entity.attributes.temperature :
          #             entity.attributes.current_temperature;
          #         }
          #       ]]]

          - type: custom:button-card
            entity: media_player.living_room_tv
            name: TV
            state_display: >
              [[[
                if (variables.state == 'playing') {
                  return 'On';
                }
              ]]]
            tap_action: !include popup/tv_livingroom.yaml
            template:
              - media
              - icon_tv

          - type: custom:button-card
            entity: light.table_lamp
            name: Lamp
            template:
              - base
              - icon_table_lamp

          - type: custom:button-card
            entity: light.lightning_bolts
            name: Lightning
            template:
              - base
              - icon_lightning_bolt

      #################################################
      #                                               #
      #                    Kitchen                    #
      #                                               #
      #################################################

      - type: grid
        title: Kitchen
        view_layout:
          grid-area: kitchen
        columns: 2
        cards:
          - type: custom:button-card
            template:
              - light
              - icon_light_group
            entity: light.kitchen_lights #kitchen_lights
            name: Lights
            tap_action: !include popup/lights_kitchen.yaml
            hold_action:
              action: toggle
              haptic: medium

          - type: custom:button-card
            entity: media_player.wall_speaker
            name: Wall Speaker
            template:
              - popup_media
              - icon_nest_mini

          # - type: custom:button-card
          #   template:
          #     - media
          #     - icon_tv
          #   entity: media_player.living_room_tv
          #   name: TV
          #   tap_action: !include popup/tv_livingroom.yaml

          # - type: custom:button-card
            # entity: switch.kettle
            # name: Kettle
            # triggers_update:
            #   - lock.dator
            #   - script.home_leave
            # hold_action: !include popup/studio_dator.yaml
            # template:
              # - base
              # - icon_imac
              # - loader
              # - lock

          - type: custom:button-card
            entity: light.kitchen_west
            name: Left
            template:
              - light
              - icon_spot

          - type: custom:button-card
            entity: light.kitchen_east
            name: Right
            template:
              - light
              - icon_spot

          # - type: custom:button-card
          #   entity: switch.wemo_monitors
          #   name: Monitorer
          #   triggers_update: sensor.monitors_volume
          #   hold_action: !include popup/studio_monitorer.yaml
          #   template:
          #     - base
          #     - icon_monitors
          #     - circle
          #     - loader
          #   variables:
          #     circle_input: >
          #       [[[
          #         var entity_id = 'sensor.monitors_volume';
          #         return states[entity_id] === undefined ? null : states[entity_id].state;
          #       ]]]

      #################################################
      #                                               #
      #                    BEDROOM                    #
      #                                               #
      #################################################

      - type: grid
        title: Bedroom
        view_layout:
          grid-area: bedroom
        columns: 2
        cards:
          
          - type: custom:button-card
            template:
              - light
              - icon_light_group
            entity: light.bedroom_lights #bedroom_lights
            name: Lights
            tap_action: !include popup/lights_bedroom.yaml
            hold_action:
              action: toggle
              haptic: medium

          - type: custom:button-card
            entity: media_player.bedroom_tv
            name: "TV"
            tap_action: !include popup/tv_bedroom.yaml
            state_display: >
              [[[
                if (variables.state == 'playing') {
                  return 'On';
                }
              ]]]
            template:
              - media
              - icon_tv

          - type: custom:button-card
            entity: light.bed
            name: Bed LEDs
            template:
              - light
              - icon_light_strip
              # - icon_hue

          - type: custom:button-card
            entity: media_player.bedroom_speaker
            name: Bedroom Speaker
            template:
              - popup_media
              - icon_nest_mini

          # - type: custom:button-card
          #   entity: switch.bedroom_monitor
          #   name: "Monitor"
          #   hold_action: !include popup/sovrum_tv2.yaml
          #   template:
          #     - base
          #     - icon_tv

      #################################################
      #                                               #
      #                     MEDIA                     #
      #                                               #
      #################################################

      - type: grid
        title: Media
        view_layout:
          grid-area: media
        columns: 1
        cards:
          # - type: custom:mod-card
          #   style:
          #     swipe-card:
          #       $: |
          #         .swiper-container {
          #           padding: 0px 0px 20px 0px !important;
          #         }
          - type: "custom:swipe-card"
            start_card: 1
            parameters:
              roundLengths: true
              effect: coverflow
              speed: 650
              spaceBetween: 20
              threshold: 7
              coverflowEffect:
                rotate: 80
                depth: 300
            cards:
              - type: grid
                columns: 2
                cards:
                  - type: custom:button-card
                    entity: media_player.living_room_tv
                    tap_action: !include popup/tv_livingroom.yaml
                    name: LR TV
                    template:
                      - media
                      - icon_tv

                  - type: custom:button-card
                    entity: media_player.living_room_speaker
                    name: LR Speaker
                    template:
                      - popup_media
                      - icon_google_home

                  - type: custom:button-card
                    name: Bedroom TV
                    entity: media_player.bedroom_tv
                    tap_action: !include popup/tv_bedroom.yaml
                    template:
                      - media
                      - icon_tv

                  - type: custom:button-card
                    entity: media_player.bedroom_speaker
                    name: BR Speaker
                    template:
                      - popup_media
                      - icon_nest_mini

              - type: horizontal-stack
                cards:
                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Living Room TV
                    card:
                      type: custom:button-card
                      entity: media_player.living_room_tv
                      template:
                        - conditional_media
                        - icon_tv

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Living Room Speaker
                    card:
                      type: custom:button-card
                      entity: media_player.living_room_speaker
                      template:
                        - conditional_media
                        - icon_google_home

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Bedroom TV
                    card:
                      type: custom:button-card
                      entity: media_player.bedroom_tv
                      template:
                        - conditional_media
                        - icon_tv

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Bedroom Speaker
                    card:
                      type: custom:button-card
                      entity: media_player.bedroom_speaker
                      template:
                        - conditional_media
                        - icon_nest_mini

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Wall Speaker
                    card:
                      type: custom:button-card
                      entity: media_player.wall_speaker
                      template:
                        - conditional_media
                        - icon_nest_mini

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Spotify
                    card:
                      type: custom:button-card
                      entity: media_player.spotify
                      template:
                        - conditional_media
                        - icon_spotify

                  - type: conditional
                    conditions:
                      - entity: input_select.conditional_media
                        state: Last Downloaded
                    card:
                      type: custom:button-card
                      entity: sensor.plex_recently_added
                      tap_action:
                        action: none
                      template:
                        - conditional_media
                        - recently_downloaded
                        - icon_plex

      #################################################
      #                                               #
      #                    OTHER                      #
      #                                               #
      #################################################

      - type: grid
        title: Other
        view_layout:
          grid-area: other
        columns: 2
        cards:
          - type: custom:button-card
            entity: light.bathroom
            name: Bathroom
            template:
              - light
              - icon_bathroom

          - type: custom:button-card
            entity: switch.fan
            name: "Fan"
            template:
              - base
              - icon_fan2
              - loader

          - type: custom:button-card
            entity: light.hallway
            name: Hallway
            template:
              - light
              - icon_spot
              

          - type: custom:button-card
            name: Schedules
            show_state: false
            icon: mdi:clock-outline
            tap_action: !include popup/scheduler.yaml
            template:
              - base
              - icon_schedules

      #################################################
      #                                               #
      #                     HOME                      #
      #                                               #
      #################################################

      - type: grid
        title: Home
        view_layout:
          grid-area: home
        columns: 2
        cards:
          - type: custom:button-card
            entity: person.dave
            name: Dave
            triggers_update:
              - device_tracker.davecom
            tap_action: !include popup/person_dave.yaml
            hold_action:
              action: none
            variables:
              retain: sensor.sanja_last_changed
            template: person

          - type: custom:button-card
            name: Schedules
            show_state: false
            icon: mdi:clock-outline
            tap_action: !include popup/person_ebony.yaml
            template:
              - base
              - icon_schedules

          # - type: custom:button-card
          #   entity: person.ebony
          #   name: Ebony
          #   triggers_update:
          #     - device_tracker.ebonycom
          #   tap_action: !include popup/person_ebony.yaml
          #   hold_action:
          #     action: none
          #   variables:
          #     retain: sensor.sanja_last_changed
          #   template: person
            
          - type: custom:button-card
            template:
              - light
              - icon_light_home
            entity: light.all_lights_except_lightning_bolts_and_closet #all_lights_except_lightning_bolts_and_closet
            name: All Lights
            tap_action: !include popup/lights_main.yaml
            hold_action:
              action: toggle
              haptic: medium

          - type: custom:button-card
            entity: climate.thermostat
            name: Heating
            tap_action: !include popup/sovrum_klimat.yaml
            hold_action:
              !include popup/sovrum_klimat.yaml
            template:
              - base
              - icon_climate
              - climate
            variables:
              circle_input: >
                [[[
                  if (entity) {
                    return entity.state == 'heat' ?
                      entity.attributes.temperature :
                      entity.attributes.current_temperature;
                  }
                ]]]

      #################################################
      #                                               #
      #                    FOOTER                     #
      #                                               #
      #################################################

      # - type: custom:button-card
      #   view_layout:
      #     grid-area: footer
      #   entity: sensor.time
      #   template: coronavirus
