homeassistant:
  customize:

    ####################################################
    #                                                  #
    #                    CUSTOMIZE                     #
    #                                                  #
    ####################################################

    media_player.spotify:
      friendly_name: Spotify
    switch.kettle:
      icon: mdi:kettle
    switch.blanket:
      icon: mdi:bed-outline
    switch.fan:
      icon: mdi:fan
    switch.space_heater:
      icon: mdi:fireplace
    light.bathroom:
      icon: mdi:shower
    switch.lightning_red:
      icon: mdi:lightning-bolt-outline
    switch.lightning_purple_1:
      icon: mdi:lightning-bolt-outline
    switch.lightning_purple_2:
      icon: mdi:lightning-bolt-outline
    light.lightning_red:
      icon: mdi:lightning-bolt-outline
    light.lightning_purple_1:
      icon: mdi:lightning-bolt-outline
    light.lightning_purple_2:
      icon: mdi:lightning-bolt-outline
    light.chandelier:
      icon: mdi:ceiling-light
    light.bed:
      icon: mdi:bed-king-outline
    scene.morning:
      icon: mdi:white-balance-sunny
    scene.evening:
      icon: mdi:weather-sunset
    scene.normal:
      icon: mdi:brightness-5
    scene.goodnight:
      icon: mdi:moon-waxing-crescent
    scene.movie_time:
      icon: mdi:video-vintage
    scene.sexy_time:
      icon: mdi:heart-pulse
    scene.dinner_time:
      icon: mdi:food-fork-drink
    scene.toilet:
      icon: mdi:flashlight
    scene.dinner_and_a_movie:
      icon: mdi:food-fork-drink
    script.morning:
      icon: mdi:white-balance-sunny
    script.evening:
      icon: mdi:weather-sunset
    script.normal:
      icon: mdi:brightness-5
    script.goodnight:
      icon: mdi:moon-waxing-crescent
    script.movie_time:
      icon: mdi:video-vintage
    script.sexy_time:
      icon: mdi:heart-pulse
    script.dinner_time:
      icon: mdi:food-fork-drink
    script.toilet:
      icon: mdi:flashlight
    script.dinner_and_a_movie:
      icon: mdi:food-fork-drink
    # #light
    # light.vardagsrum_group:
    #   friendly_name: Belysning
    #   icon: mdi:lamp
    # light.dator:
    #   friendly_name: Datorlampa
    # light.sovrum:
    #   friendly_name: Sänglampor
    #   icon: mdi:floor-lamp

    # #esphome
    # sensor.gosund_1_daily_energy:
    #   friendly_name: gosund_1_da
    # sensor.gosund_2_daily_energy:
    #   friendly_name: Electrolux ChillFlex Pro Gold
    # sensor.gosund_3_daily_energy:
    #   friendly_name: gosund_3_da

    # #media_player
    # media_player.sony_bravia_tv:
    #   friendly_name: Tv
    #   device_class: tv
    # media_player.samsung_tv:
    #   friendly_name: "Tv\u00B2"
    #   device_class: tv
    # media_player.kok:
    #   friendly_name: Google Nest Mini

    # #binary_sensor
    # binary_sensor.sensor_hall_motion:
    #   friendly_name: hallen
    # binary_sensor.sensor_badrum_motion:
    #   friendly_name: badrummet
    # binary_sensor.sensor_garderob_motion:
    #   friendly_name: klädkammaren
    # binary_sensor.wemo_motion:
    #   friendly_name: vardagsrummet

    # #battery
    # sensor.switchbot_battery:
    #   friendly_name: Switchbot
    #   device_class: battery
    # sensor.dimmer_badrum_battery_level:
    #   friendly_name: Dimmer Badrum
    # sensor.dimmer_sovrum_battery_level:
    #   friendly_name: Dimmer Sovrum
    # sensor.sensor_hall_battery:
    #   friendly_name: Sensor Hall
    # sensor.sensor_garderob_battery:
    #   friendly_name: Sensor Garderob
    # sensor.sensor_badrum_battery:
    #   friendly_name: Sensor Badrum

    # #fan
    # fan.studio_wemo:
    #   icon: custom:pedestal-fan

    # # template.yaml
    # select.vacuum_speed:
    #   friendly_name: Rengöringsläge
    #   icon: mdi:format-list-bulleted
    # select.hdmi_bravia:
    #   friendly_name: Källa
    #   icon: custom:hdmi-source
    # select.hdmi_samsung:
    #   friendly_name: Källa
    #   icon: custom:hdmi-source

    # #vardagsrum_balkong.yaml
    # switch.deltaco_sh_p01:
    #   friendly_name: Balkong
    #   icon: mdi:lightbulb-variant
    # automation.balcony:
    #   friendly_name: Tänd ljusslinga med rörelsedetektor

    # #sidebar_vacuum.yaml
    # vacuum.morty:
    #   friendly_name: Roborock S5
    #   icon: custom:roborock-vacuum
    # sensor.morty_last_clean_end:
    #   friendly_name: Senast städat
    #   icon: mdi:calendar-clock

    # #sidebar_information.yaml
    # switch.watchtower:
    #   icon: custom:docker-watchtower
    # sensor.databas:
    #   icon: mdi:database
    # sensor.home_assistant_log:
    #   friendly_name: Loggfil
    #   icon: mdi:file-document
    # sensor.uptime:
    #   friendly_name: Senast omstart
    #   icon: mdi:update
    #   device_class: timestamp
    # sensor.docker_cpu:
    #   friendly_name: Processor
    #   icon: mdi:chip
    # switch.galaxy_tab_a_screensaver:
    #   friendly_name: Skärmsläckare
    #   icon: mdi:power-sleep
    # light.galaxy_tab_a_screen:
    #   friendly_name: Display
    #   icon: mdi:tablet
    # binary_sensor.galaxy_tab_a_plugged_in:
    #   friendly_name: Strömtillförsel
    #   icon: mdi:power-plug
    # sensor.galaxy_tab_a_battery_level:
    #   friendly_name: Batteri
    # sensor.nas_volume_1_average_disk_temp:
    #   friendly_name: Disktemperatur
    # sensor.processor_use_percent:
    #   icon: mdi:chip

    # # vardagsrum_tv.yaml
    # automation.tv_on_lights:
    #   friendly_name: Tänd Tv-lampa

    # # studio_dator.yaml
    # sensor.imac_cpu:
    #   friendly_name: Processor
    #   icon: mdi:chip
    # sensor.imac_mem:
    #   friendly_name: Minne
    #   icon: mdi:memory
    # automation.macos_notification_motion_hall:
    #   friendly_name: Mottag notiser
    #   icon: mdi:bell
    # sensor.imac_uptime:
    #   friendly_name: Senaste omstart
    #   icon: mdi:update
    #   device_class: timestamp
    # sensor.imac_system_ssd:
    #   friendly_name: System SSD
    #   icon: custom:imac-ssd
    # sensor.imac_macintosh_hd:
    #   friendly_name: Macintosh HD
    #   icon: mdi:harddisk

    # # studio_monitorer.yaml
    # switch.wemo_monitors:
    #   friendly_name: Monitorer
    #   icon: custom:studio-monitor
    # automation.turn_off_monitors:
    #   friendly_name: Stäng av när dator stängs av
    #   icon: mdi:power
    # automation.eq_calibration:
    #   friendly_name: Automatisk kalibrationsprofil
    #   icon: custom:eq-calibrate

    # #person
    # person.matte:
    #   entity_picture: /local/mattias.png
    # sensor.mattias_weight:
    #   unit_of_measurement: kg
    # device_tracker.mattias_iphone_ios:
    #   entity_picture: /local/device_tracker.svg
    # person.sanja:
    #   entity_picture: /local/sanja.png

    # #sort
    # sensor.rpi_cpu:
    #   friendly_name: Processor
    #   icon: mdi:chip
    # sensor.rpi_mem:
    #   friendly_name: Minne
    #   icon: mdi:memory
    # sensor.rpi_sd:
    #   friendly_name: SD-kort
    #   icon: mdi:micro-sd
    # sensor.rpi_uptime:
    #   friendly_name: Senaste omstart
    #   icon: mdi:update
    #   device_class: timestamp
