action: fire-dom-event
browser_mod:
  command: popup
  title: " "
  style:
    .: |
      :host .content {
        width: calc(385px + 385px + 385px);
        max-width: 90vw;
      }
      /* phone */
      @media screen and (max-width: 800px) {
        :host .content {
          max-width: 100vw;
        }
      }
    layout-card:
      $grid-layout$:
        hui-entities-card:
          $: |
            .card-content {
              padding: 1.5em 2.7em 2.3em 2em;
            }
            ha-card {
              border-right: 1.5px solid rgba(0, 0, 0, 0.2);
              border-radius: 0;
              transition: none;
            }
            button-card {
              align-self: center !important;
              padding: 0 0 0 3.5em;
            }
            /* phone */
            @media screen and (max-width: 800px) {
              ha-card {
                border-right: none;
                border-bottom: 1.5px solid rgba(0, 0, 0, 0.2);
              }
            }
          $hui-horizontal-stack-card:
            $: |
              #root {
                justify-content: space-evenly;
                margin-top: 1.9em;
                max-width: 84vw; /* iphonex */
              }
  card:
    type: custom:layout-card
    layout_type: custom:grid-layout
    layout:
      grid-template-columns: repeat(3, 1fr)
      grid-template-rows: 1fr
      grid-template-areas: |
        "info indoor outdoor"
      mediaquery:
        #phone
        "(max-width: 800px)":
          grid-template-columns: 1fr 1fr
          grid-template-rows: repeat(3, 1fr)
          grid-template-areas: |
            "info info"
            "indoor indoor"
            "outdoor outdoor"
    cards:
      #################################################
      #                                               #
      #                HOME ASSISTANT                 #
      #                                               #
      #################################################

      - type: entities
        view_layout:
          grid-area: info
        title: Security Status
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0px !important;
            }
        entities:
          - type: section
            label: Last Opened
          - type: section
            label: Doors
          - entity: binary_sensor.front_door_is_open
            name: "Front Door"
            secondary_info: last-changed
          - entity: binary_sensor.back_door_is_open
            name: "Back Door"
            secondary_info: last-changed
          - type: section
            label: Windows
          - entity: binary_sensor.living_room_window_south_is_open
            name: Living Room South
            secondary_info: last-changed
          - entity: binary_sensor.living_room_window_west_left_is_open
            name: Living Room West (Left)
            secondary_info: last-changed
          - entity: binary_sensor.living_room_window_west_right_is_open
            name: Living Room West (Right)
            secondary_info: last-changed
          - entity: binary_sensor.kitchen_window_north_is_open
            name: Kitchen North
            secondary_info: last-changed
          - entity: binary_sensor.kitchen_window_west_left_is_open
            name: Kitchen West (Left)
            secondary_info: last-changed
          - entity: binary_sensor.kitchen_window_west_right_is_open
            name: Kitchen West (Right)
            secondary_info: last-changed
          - entity: binary_sensor.bedroom_window_east_is_open
            name: Bedroom East
            secondary_info: last-changed
          - entity: binary_sensor.bedroom_window_west_is_open
            name: Bedroom West
            secondary_info: last-changed
          - entity: binary_sensor.bathroom_window_is_open
            name: Bathroom
            secondary_info: last-changed

          # - type: section
          #   label: Camera Status
          # - entity: binary_sensor.amcrest_living_room_online
          #   name: "Living Room Camera"

      - type: entities
        view_layout:
          grid-area: indoor
        title: Inside
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0px !important;
            }
        entities:
          - type: section
            label: Last Detected Person
          - entity: binary_sensor.livingroom_person_motion
            name: "Living Room"
            secondary_info: last-changed

          - type: section
            label: Last Detected Motion
          # - entity: binary_sensor.amcrest_living_room_motion_detected
          #   name: "Living Room"
            secondary_info: last-changed
          - entity: binary_sensor.kitchen_motion_detected
            name: "Kitchen"
            secondary_info: last-changed

          - type: "custom:frigate-card"
            cameras:
              - camera_entity: camera.livingroom
                title: Living Room
                id: living_room_id
                live_provider: webrtc-card
                webrtc_card:
                  url: !secret cam_rtsp_living_room
                  camera_name: Living Room
            live:
              webrtc_card:
                ui: false
                background: false
              preload: false
            view:
              actions:
                double_tap_action:
                  action: custom:frigate-card-action
                  frigate_card_action: fullscreen
            overrides:
              - conditions:
                  camera:
                    - camera.livingroom
                    - living_room_id
                overrides:
                  menu:
                    buttons:
                      frigate: false
                      fullscreen: true

      - type: entities
        view_layout:
          grid-area: outdoor
        title: Outside
        show_header_toggle: false
        card_mod:
          class: header
          style: |
            ha-card {
              margin: 0px !important;
            }
        entities:
          - type: section
            label: Doors
          - type: section
            label: Last Detected Motion
          - entity: sensor.doorbell_last_motion
            name: "Front Door"
          - type: section
            label: Street
          - type: "custom:frigate-card"
            cameras:
              - camera_entity: camera.street
                camera_name: Street
                id: street_id
                live_provider: webrtc-card
                webrtc_card:
                  url: rtsp://homeassistant.local:8554/street
            live:
              webrtc_card:
                ui: false
                background: false
              preload: false
            view:
              actions:
                double_tap_action:
                  action: custom:frigate-card-action
                  frigate_card_action: fullscreen
            overrides:
              - conditions:
                  camera:
                    - camera.street
                    - street_id
                overrides:
                  menu:
                    # mode: none
                    buttons:
                      frigate: false
                      fullscreen: true
          - type: section
            label: Doors
          - type: "custom:frigate-card"
            cameras:
              - camera_entity: camera.driveway
                camera_name: Driveway
                id: driveway_id
                live_provider: webrtc-card
                webrtc_card:
                  url: !secret cam_rtsp_driveway
              - camera_entity: camera.backdoor
                camera_name: Backdoor
                id: backdoor_id
                live_provider: webrtc-card
                webrtc_card:
                  url: rtsp://homeassistant.local:8554/backdoor
              - camera_entity: camera.doorbell
                camera_name: Doorbell
            live:
              webrtc_card:
                ui: false
                background: true
              preload: true
            view:
              actions:
                double_tap_action:
                  action: custom:frigate-card-action
                  frigate_card_action: fullscreen
            overrides:
              - conditions:
                  camera:
                    - camera.driveway
                    - driveway_id
                    - camera.backdoor
                    - backdoor_id
                    - camera.doorbell
                overrides:
                  menu:
                    # mode: none
                    buttons:
                      frigate: false
                      fullscreen: true

          - type: custom:button-card
            name: Stream Street on TV
            icon: mdi:cast
            template: icon_name
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.dashcast_street_to_tv
                # entity_id: script.cast_street_to_tv

          - type: custom:button-card
            name: Stream Driveway on TV
            icon: mdi:cast
            template: icon_name
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.dashcast_driveway_to_tv
                # entity_id: script.cast_driveway_to_tv
